#-------------------------------
# Site Settings
title: Jube
logo: '/images/logo.png'
description: Jube is open-source transaction and event monitoring software.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Features'
      url: '/features/'
    - title: 'GitHub'
      url: 'https://github.com/jube-home/jube'
    - title: 'Docs'
      url: 'https://jube-home.github.io/jube/'
    - title: 'Blog'
      url: '/blog/'

#-------------------------------
# Author Settings
author:
  author__name: About Jube
  author__bio: Jube is born of decades of experience in transaction and event monitoring, which is growing to specialise in the domain's overlap between data engineering and machine learning.
  author__avatar: '/images/Jube.png'

social:
- {icon: "ion-logo-github", link: "https://github.com/jube-home/jube"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Open-Source Transaction and Event Monitoring
  hero__description: Jube implements real-time data wrangling, machine learning, decision making and case management. Jube is particularly strong when implemented in fraud and abuse detection use cases.
  hero__image: '/images/Jube.png'

#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Features
  projects__description: Everything to ensure effective real-time transaction and event monitoring.

#-------------------------------
# Blog Section
blog__settings:
  blog__title: Recent Posts
  blog__description:

#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Features'
      url: '/features/'
    - title: 'GitHub'
      url: 'https://github.com/jube-home/jube'
    - title: 'Docs'
      url: 'https://jube-home.github.io/jube/'
    - title: 'Blog'
      url: '/blog/'

#-------------------------------
# Google Analytics
google-analytics: G-7PYZ045CND
